### ISSUE TITLE
Preloading data automatically

### ISSUE THREAD

**Issue by vvo** [hoangvvo/next-connect#124]
Hi there, I am currently not yet using next-connect. I plan on using it still because its interface seems great.

Before I use it, I need to know how I could solve one pattern: data preloading.

Right now all my Next.js API handlers are wrapped with something like that:

/pages/api/teams/[teamId]/users
```
function teamUsersApi(req, res, preloadedData) {
  console.log(preloadedData.user);
  console.log(preloadedData.team);
}

export default withPreloadData(teamApi);
```

When I call `/api/teams/200/users` then I preload from my database the current user (from reading cookie data) and the team with id 200 (from url params). This is all done by withPreloadData which then calls the API handler with (req, res, preloadedData).

What would be the right pattern to do the same with next-connect? Attaching some property to req maybe? If so what would be the right TypeScript typings to use for that?

Thanks!

**Comment by hoangvvo** [comment]
You would have to attach some property to req.

When creating the `nc` instance just define the type there.

```ts
const handler = nc<NextApiRequest & { team: Team | null, user: User | null }, NextApiResponse>

handler.use(async (req, res, next) => {
  req.user = await getUser(req.cookies);
  req.team = await getTeam(req.query.teamId);
});

handler.get((req, res) => {
  console.log(req.user);
  console.log(req.team);
})

handler.post((req, res) => {
  console.log(req.user);
  console.log(req.team);
})
```

If `user` and `team` property only exists on a specific handler. You can define the generic per handler.

```ts
const handler = nc<NextApiRequest, NextApiResponse>

handler.use<{ team?: Team | null, user?: User | null }>(async (req, res, next) => {
  if (req.method !== "POST") return next();
  req.user = await getUser(req.cookies);
  req.team = await getTeam(req.query.teamId);
  next();
})

handler.get((req, res) => {
  console.log(req.user); // No
  console.log(req.team); // No
})

handler.post<{ team: Team | null, user: User | null }>((req, res) => {
  console.log(req.user);
  console.log(req.team);
})
```

Basically whatever generics provided per handler get merged with the ones provided when creating the instance.
