### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by hoangvvo** [hoangvvo/next-connect#126]
This library has been sitting in v0 for awhile. After a period of using it in several production apps, it does not seem to yield any problems. After all, most crux of this library depends on the awesome https://github.com/lukeed/trouter library, so nothing much can really go wrong.

Before the 1.0 release though:
- I want to make sure the APIs are reasonable so that we can avoid breaking changes to it.
- Update documentation to be more general. Even though this is originally built of Next.js, I have been using it on top on `http` very fine. Therefore, it should be about more than Next.js.
- Decide on whether to add several features like routing caching to improve perf. I have been debating this since one of the goal of this library is to stay lightweight.
- Decide on whether to add several utils like middleware concurrent execution

**Comment by qnxdev** [comment]
How to use it with GrahQL

If I use it in my production build, how difficult could it be to switch to expressjs later?

**Comment by hoangvvo** [comment]
You can always switch to express by replace `nc()` with `express()`. Regarding GraphQL, you probably use it with something like express-graphql, in which case their example works simply by replacing `express()` with `nc()`

**Comment by qnxdev** [comment]
What about using GraphQL with next-connect? And even if I achieve it will it work on Vercel serverless?

**Comment by hoangvvo** [comment]
It definitely works:

```js
// api/graphql.js
const nc = require("next-connect");
const { graphqlHTTP } = require("express-graphql");

module.exports = nc()
  .use(middleware)
  .all(graphqlHTTP({
    schema: MyGraphQLSchema
  }));
```

**Comment by stigkj** [comment]
Would it be smart to include support for the new middleware support in Next.js? Or do you see that as a v2? Or never ;-)

**Comment by hoangvvo** [comment]
> Would it be smart to include support for the new middleware support in Next.js? Or do you see that as a v2? Or never ;-)

It is totally possible. I am just wondering what would be a good export for this functionality:

```
import nc from "next-connect/next-middleware
// or
import { middleware } from "next-connect"
```

**Comment by stigkj** [comment]
I think I would go with the second one.
