### ISSUE TITLE
Cors in next.js API routes - does not seem to work?

### ISSUE THREAD

**Issue by w90** [hoangvvo/next-connect#127]
Did anyone get the `next-connect` package to work with `cors` package and the relatively new next.js feature - [API routes](https://nextjs.org/docs/api-routes/introduction)?

pages/api/process file:
```js
import nextConnect from 'next-connect';
import Cors from 'cors'

const apiRoute = nextConnect();

apiRoute
  .use(Cors())

  .post((req, res) => {
    res.status(200).json({ text: 'OK' })
  })

export default apiRoute;
```

Additional settings in next.config.js:
```js
module.exports = {
  async headers() {
    return [
      {
        source: '/api/process',
        headers: [
          {
            key: 'Access-Control-Allow-Origin',
            value: 'https://external-webpage.com',
          },
          {
            key: 'Vary',
            value: 'Origin',
          },
        ],
      },
    ]
  },
}
```

I'm getting cors related errors. I might be doing something wrong, if so please correct me!

Meanwhile, when using [example from next.js repo](https://github.com/vercel/next.js/tree/canary/examples/api-routes-cors), which does not utilize next-connect library, all works just fine:

Any advice will be much appreciated, as I'd rather use next-connect solution which is imo a bit cleaner than the one provided by the next.js team.

**Comment by hoangvvo** [comment]
I am also using the cors package and have no problems. What errors are you seeing?

**Comment by w90** [comment]
Hello, thanks for the reply. It's the standard cors error, 'Access-Control-Allow-Origin' etc.
As I stated in my detailed post above, all works fine when using the next.js example, without next-connect.
Could you maybe paste here, what is your exact implementation, when using next.js API Routes?
Much appreciated!

**Comment by hoangvvo** [comment]
@w90 Hey, I could not reproduce this issue: https://codesandbox.io/s/next-connect-with-cors-package-guned?file=/pages/api/index.js

Please provide a complete reproduction if possible. Thanks!

**Comment by w90** [comment]
Hello Hoang, thanks a lot for the reply!
I've found the bug in the code - it was the missing trailing slash on the original api endpoint `/api/process`.
Everything works perfect!
I'm closing the issue.
Peace!
