### ISSUE TITLE
Render a page back to client

### ISSUE THREAD

**Issue by maxy4u** [hoangvvo/next-connect#139]
Hi,
This is more of a question and not an issue.
I am trying to build one logic to redirect to 401.js page in next js  from our api if user is not authenticated. I know we can do res.status 302 and then location param will redirect. However, the status code 30* will not do justice to 401 page.
Is there a way to render a page back to client like in express we have render method ?

Thanks in advance.
Regards
Gaurav

**Comment by hoangvvo** [comment]
You can try to make use of `app.render` from https://nextjs.org/docs/advanced-features/custom-server but I have not tried it yet.
