### ISSUE TITLE
getServerSideProps api call

### ISSUE THREAD

**Issue by m4tta** [hoangvvo/next-connect#147]
So how exactly do I get the returned JSON from one of my API routes when trying to run the handler in getServerSideProps?

**Comment by hoangvvo** [comment]
I am not sure that I understand. Could you please describe your use case in more detail?

**Comment by m4tta** [comment]
When you call one of your NextJS API routes like described here

https://github.com/hoangvvo/next-connect#runreq-res
`await handler.run(req, res);`

If that API route returns JSON. How do you access that JSON data returned from the handler?

**Comment by hoangvvo** [comment]
Okay I understood. `handler.run` is getServerSideProps is not mean to send a response (so you probably don't want to call res.end or similar in there). It is only used to allow middleware to "decorate" (add properties like `req.user` to `req`).

**Comment by nemanjam** [comment]
> 

What about types?

```ts
export const getServerSideProps: GetServerSideProps = async ({ req, res, params }) => {
  const id = Number(params?.id);
  // try catch...

  const handler = nc(ncOptions).use(async (req, res, next) => {
    req.result = await getPostWithAuthorById(id);
    next();
  });

  await handler.run(req as NextApiRequest, res as NextApiResponse);
  const post = req.result;
```

![image](https://user-images.githubusercontent.com/9990165/162710565-7fe95180-4035-47bc-a430-a0268603bf7d.png)

![image](https://user-images.githubusercontent.com/9990165/162710635-49945205-60d4-4d3c-b94a-78c4d0db527a.png)

**Comment by hoangvvo** [comment]
> > 
> 
> What about types?
> 
> ```ts
> export const getServerSideProps: GetServerSideProps = async ({ req, res, params }) => {
>   const id = Number(params?.id);
>   // try catch...
> 
>   const handler = nc(ncOptions).use(async (req, res, next) => {
>     req.result = await getPostWithAuthorById(id);
>     next();
>   });
> 
>   await handler.run(req as NextApiRequest, res as NextApiResponse);
>   const post = req.result;
> ```
> 
> ![image](https://user-images.githubusercontent.com/9990165/162710635-49945205-60d4-4d3c-b94a-78c4d0db527a.png)

Can you try the TypeScript section https://github.com/hoangvvo/next-connect#typescript? The types you want to use can be found here:

![image](https://user-images.githubusercontent.com/40987398/162790395-5d4e3ca5-4651-4622-acd0-25c40a4b0611.png)
