### ISSUE TITLE
graphql-shield

### ISSUE THREAD

**Issue by Manubi** [hoangvvo/next-connect#155]
Hey,
can anyone tell my how I would I use next-connect with `graphql-shield` https://graphql-shield.vercel.app/docs ? Because my idea is to use `next-connect` instead of `graphql-middleware`

thanks!

**Comment by hoangvvo** [comment]
I don't think it is possible, `graphql-shield` seems to be rewritten to support `graphql-middleware`, which applies effects on GraphQL resolvers, and not HTTP Handler (which next-connect deals with).

**Comment by Manubi** [comment]
Hi,
thanks! :)
cheers
