### ISSUE TITLE
Right way to use instance of next-connect?

### ISSUE THREAD

**Issue by IRediTOTO** [hoangvvo/next-connect#158]
Hi, I export a var like this and use it all my API. Is this the right way to use? My API sometimes returns nothing, no errors

```
export const handler = nc<NextApiRequest, NextApiResponse>({
    onError: (err, req, res, next) => {
        return res.status(500).json({ success: false })
    },
    onNoMatch: (req, res) => {
        return res.status(404).json({ success: false })
    },
})

```

**Comment by hoangvvo** [comment]
As mentioned in the README, this is an anti pattern, so you shouldn't use it

> DO NOT reuse the same instance of nc like the below pattern
