### ISSUE TITLE
Yarn berry PnP + Next.js 12 has import error.

### ISSUE THREAD

**Issue by minkichoe** [hoangvvo/next-connect#163]
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'next-connect' imported from /app/.next/server/pages/api/test_endpoint.js

**Comment by MatsG23** [comment]
The ESM support for PnP in yarn is still experimental. Meanwhile, you can set `nodeLinker` to `node-modules` in the yarn config file.

Sources:
https://github.com/yarnpkg/berry/issues/638
https://nodejs.org/api/esm.html#esm_loaders ("Stability: Experimental")

**Comment by hoangvvo** [comment]
I'm not familiar with Yarn PNP. Does a library author have to config their library is a specific way to work with Yarn PnP? My assumption was that it should just work.

**Comment by MatsG23** [comment]
On the top of the issue I sent, the user says:
_In case you reach this thread by Twitter, ESM for PnP is on our roadmap. It's tricky due to some primitives currently missing in Node (they're working on this, but as you can see it's still branded as experimental), in the meantime if you need it then the node-modules linker remain a perfectly fine solution._

Nonetheless the issue has existed for a long time and it will probably take a lot more time...
I know that TypeScript can compile a "module" (ESM = ECMAScript Module) down to "CommonJS". Since your package is pure JS, I think all you/we can do is:
A) wait for NodeJS to make the ESM Loader stuff stable (probably Yarn is faster although it's tricky)

B) make your code non-modular, which may have downsides I don't know. The `type: "module"` in the `package.json` makes  the project a module

**Comment by dtothefp** [comment]
I just ran into this issue as well when enabling SWC compiler when using Yarn Berry PNP. Can't quite tell from the yarn GH issue if this is resolved or not 🤷 

https://github.com/yarnpkg/berry/issues/638

**Comment by hoangvvo** [comment]
next-connect is provided with both ESM and commonjs version. 

As it appears to be due to Yarn PnP not handling ESM probably, we can try to disable ESM in Next.js. One can also try to patch next-connect package.json to remove any reference of ESM (remove the exports field, leaving only the main field)

**Comment by ceefour** [comment]
Using `nodeLinker: pnp` with nextjs 12.x is quite flaky. But sometimes when you're lucky, with the addition of `yarn unplug next`, it can work.

* nextjs 12.0.1 (unplugged) + @urql/auth-exchange : works
* nextjs 12.0.2/12.0.3/12.04 (unplugged) + @urql/auth-exchange : `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@urql/auth-exchange' imported from ...`

**Comment by MatsG23** [comment]
> next-connect is provided with both ESM and commonjs version.
> 
> As it appears to be due to Yarn PnP not handling ESM probably, we can try to disable ESM in Next.js.
> 
> One can also try to patch next-connect package.json to remove any reference of ESM (remove the exports field, leaving only the main field)
> 
> ```diff
> {
>   "name": "next-connect",
>   "version": "0.11.0",
>   "description": "The method routing and middleware layer for Next.js (and many others)",
>   "keywords": [
>     "javascript",
>     "nextjs",
>     "middleware",
>     "router",
>     "connect"
>   ],
> -  "type": "module",
>   "main": "dist/index.cjs",
> -  "module": "dist/index.js",
>   "types": "dist/index.d.ts",
>   "files": [
>     "dist"
>   ],
> -  "exports": {
> -    ".": {
> -      "require": "./dist/index.cjs",
> -      "import": "./dist/index.js"
> -    }
> -  }
> }
> ```

Sounds promising. How to test that? I've never made a own npm plugin and have no idea how to do that.

**Comment by merceyz** [comment]
Should have been fixed in https://github.com/yarnpkg/berry/pull/3667
```sh
yarn set version canary && yarn install
```

> Does a library author have to config their library is a specific way to work with Yarn PnP?

@hoangvvo No, as long as you declare all the dependencies you use and use Node builtins to deal with resolving modules everything should just work on its own

**Comment by hoangvvo** [comment]
> Should have been fixed in https://github.com/yarnpkg/berry/pull/3667
> ```sh
> yarn set version canary && yarn install
> ```
> 
> > Does a library author have to config their library is a specific way to work with Yarn PnP?
> 
> @hoangvvo No, as long as you declare all the dependencies you use and use Node builtins to deal with resolving modules everything should just work on its own

Awesome work! Thanks a lot

**Comment by minkichoe** [comment]
I solved this problem after changing Docker settings.
But I think merceyz's solution is right for the fundamental problem and solution.
Thanks!

\* My new Dockerfile.prod
```
FROM node:alpine AS builder
ENV NODE_ENV production

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY . .

RUN yarn rebuild && yarn build

# Production image, copy all the files and run next
FROM node:alpine AS runner

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

ENV NODE_ENV production
WORKDIR /app

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/.yarnrc.yml ./.yarnrc.yml
COPY --from=builder /app/.pnp.loader.mjs ./.pnp.loader.mjs
COPY --from=builder /app/package.json ./package.json

# Note yarn rebuild again - this is to let yarn rebuild binaries in the "runner" stage of the Dockerfile
# We also have to remove unplugged, so that rebuilding happens and replaces the old binaries
RUN rm -rf /app/.yarn/unplugged && yarn rebuild
RUN chown -R nextjs:nodejs /app/.next

RUN yarn set version berry
RUN yarn install --immutable --immutable-cache

USER nextjs
EXPOSE 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```
