### ISSUE TITLE
Socket IO

### ISSUE THREAD

**Issue by kotsh23** [hoangvvo/next-connect#165]
Hello guys

i want ask if there is way to implement socket io with next-connect because i use next-connect in every nextjs project 🗡️ 
i want to use it too with socket io

**Comment by hoangvvo** [comment]
The ability of using socker-io is not really related to the `next-connect`. If one can use it with Next.js, it can be used with `next-connect` since this library only concern of the routing part. However, from my knowledge, one cannot really use socket-io in next.js without a custom server.
