### ISSUE TITLE
How can I access raw request body?

### ISSUE THREAD

**Issue by lumenwrites** [hoangvvo/next-connect#169]
Hi! I'm trying to set up Stripe webhooks in my app, and for them to work, they [say](https://github.com/stripe/stripe-node#webhook-signing):
> Please note that you must pass the raw request body, exactly as received from Stripe, to the constructEvent() function; this will not work with a parsed (i.e., JSON) request body.

How can I access the "raw request body" if I'm using next-connect?

**Comment by 1aerostorm** [comment]
Next-connect is not parses your `req.body`.
Next.js does.

So, follow [this](https://nextjs.org/docs/api-routes/api-middlewares), after your...
```js
export default handler;
```
...add following:
```js
export const config = {
  api: {
    bodyParser: false,
  },
}
```

Install `micro` library:
```js
npm install micro
```

And to parse body do that:
```js
import { buffer, } from 'micro';
...
// do it in each your route handler
// or create next-connect middleware and do it in middleware
const rawBody = (await buffer(req)).toString();
```

**Comment by lumenwrites** [comment]
This worked perfectly!

Thank you so much for your help, it would've taken me forever to figure this out.
