### ISSUE TITLE
TypeScript: Property 'status', 'send', ..etc does not exist on type 'ServerResponse'

### ISSUE THREAD

**Issue by miladezzat** [hoangvvo/next-connect#175]
Hello @hoangvvo 

The methods `status`, `send`, `json`, `end` and ...etc,  don't exists on the `ServerResponse`.

**Comment by hoangvvo** [comment]
Are you using TypeScript in API Routes? Make sure to use the proper type as shown in the README: https://github.com/hoangvvo/next-connect#typescript.
