### ISSUE TITLE
ErrorHandler type miss `next` type

### ISSUE THREAD

**Issue by 22mahmoud** [hoangvvo/next-connect#180]
I found on this [commit](https://github.com/hoangvvo/next-connect/commit/d9de767b66b91badc56e02dd16de895c322a626f#diff-619cc2239a7eb4ef05041767e6ab0e4fb069e98ee9d2c83c2d8e1865c475e141L17) the `next` has been deleted from `ErrorHandler` type. 

I believe we still need it, correct?

**Comment by hoangvvo** [comment]
Sorry about that. I accidentally remove it in one of the changes.
