### ISSUE TITLE
Same API handler called when reload

### ISSUE THREAD

**Issue by develoQ** [hoangvvo/next-connect#181]
reproduce: https://github.com/develoQ/next-connect-issue-repro
```js
  useEffect(() => {
    const f = async() => {
      const res1 = await fetch("/api/hello1");
      console.log(await res1.json()) // ex) first render=> hello1 , reload after first rende => hello2
      const res2 = await fetch("/api/hello2");
      console.log(await res2.json()) // ex) first render=> hello2 , reload after first rende => hello2
    }
    f()
  },[])
```
Call 2 api from frontend. 
- /api/hello1
- /api/hello2

First render, 
Both hello1, hello2 are correctly called.

after first render, when Reload,
A is called twice or B twice.

frontend log
![スクリーンショット 2022-03-08 23 32 10](https://user-images.githubusercontent.com/69445828/157258655-51266ddd-dfc3-4873-957d-360834c88c69.png)

backend log
<img width="115" alt="スクリーンショット 2022-03-08 23 32 56" src="https://user-images.githubusercontent.com/69445828/157258813-c4823ae1-9cc2-4bf0-8d12-150d977502b9.png">

Looking at backend log, api path is correct but path handling is something wrong.

**Comment by hoangvvo** [comment]
Could you share the code that uses `next-connect` please?

**Comment by hoangvvo** [comment]
This is due to the same handler being reused (from `./handler`). This is already noted in the README: https://github.com/hoangvvo/next-connect#common-errors

> DO NOT reuse the same instance of nc like the below pattern:
> ```
> // middleware/common
> export default nc().use(a).use(b);
> 
> // api/foo
> import Handler from "middleware/common";
> export default Handler.get(x);
> 
> // api/bar
> import Handler from "middleware/common";
> export default Handler.get(y);
> ```

**Comment by develoQ** [comment]
Sorry for the lack of reading of the document.

Thanks.
