### ISSUE TITLE
TypeScript - NextConnect not compatible with NextApiHandler

### ISSUE THREAD

**Issue by osdiab** [hoangvvo/next-connect#182]
I'm using `next-connect` with `@sentry/nextjs`, and the `withApiAuthRequired()` helper in that package takes an argument of `NextApiHandler` as defined in NextJS itself. However, when using `next-connect`, the `NextConnect` type isn't compatible with `NextApiHandler`, probably because `Req` and `Res` can be any type - so I'm forced to cast it to make TypeScript not complain. Would be nice if the types lined up so that wouldn't need a cast. Would be nice if I didn't need to.

**Comment by hoangvvo** [comment]
Did you set the generics as shown in the README section at https://github.com/hoangvvo/next-connect#typescript?

**Comment by osdiab** [comment]
oh i didn't realize it, thanks for pointing that out! I'll close this.
