### ISSUE TITLE
hiding error stacktrace

### ISSUE THREAD

**Issue by mangrove108** [hoangvvo/next-connect#186]
I am currently in dev and next-connect shows the whole error stacktrace to the frontend (client) is this intended ? using nextjs. Couldnt find any hide mechanism ! Thanks

**Comment by hoangvvo** [comment]
You should define the [`onError`](https://github.com/hoangvvo/next-connect#optionsonerror) function:

```js

const handler = nc({
  onError: (err, req, res, next) => {
    console.error(err.stack); // log error
    res.status(500).end("Something broke!"); // show a specific message
  },
})
```
