### ISSUE TITLE
how to order the response [onNoMatch]

### ISSUE THREAD

**Issue by a7medmo7med9** [hoangvvo/next-connect#188]
when i send request to **post** method with **get** method it works and i don't even use get method on this url

![1](https://user-images.githubusercontent.com/34967435/167142340-e159e94f-1cea-4b76-8315-1673014b7f5f.PNG)

my code 

![2](https://user-images.githubusercontent.com/34967435/167145053-1c47504a-fb1a-4e42-808d-abca35604015.PNG)

how can i get 404 page not found on  [onNoMatch] instead of this response
```
{
  "validationErrors": {
      "email": "This Field Is Required",
      "password": "This Field Is Required"
    }
}
```

**Comment by hoangvvo** [comment]
Just to confirm that this is a valid error.

even if `.use` matches, since there is no `.METHOD`, nothing should be executed. Will be fixed in https://github.com/hoangvvo/next-connect/pull/196
