### ISSUE TITLE
.clone() returns a new instance but can not produce .handler()

### ISSUE THREAD

**Issue by BounSweFerhatSal** [hoangvvo/next-connect#206]
when creating a router as below in a separate file , to use as a base as below : 
```
import { createRouter } from "next-connect";

const pipeLineRouter = createRouter();
export default pipeLineRouter
  .use(jwtTokenValidator_middleware)
  .use(dbConnection_middleware);
```

then importing in another API file by cloning the router as below (as suggested) :

```
import apiPipeline from "/lib/apiPipeline";

const router = apiPipeline.clone();
router.get(async (req, res) => {
    //......
});

export default router.handler(errorCather);

```

router.handler() fails with error :

**TypeError: router.handler is not a function**

However, console.log(router) gives exact same router object properties which has been cloned.

**Comment by hoangvvo** [comment]
This is a bug, I am fixing it right now

**Comment by hoangvvo** [comment]
This is fixed in latest `next` version. Let me know if you still face it.
