### ISSUE TITLE
"Object.assign" in add function clear the previous stack middlewares

### ISSUE THREAD

**Issue by GeinerGV** [hoangvvo/next-connect#21]
The function doesn't always work, because **stack** property is an **Array**
```javascript
function add(method, ...handle) {
    for (let i = 0; i < handle.length; i += 1) {
      if (handle[i].stack) Object.assign(this.stack, handle[i].stack);
      else this.stack.push({ handle: handle[i], method });
    }
  }
```
a temporal solution: **Change it with a forEach and push**
```javascript
function add(method, ...handle) {
    for (let i = 0; i < handle.length; i += 1) {
      if (handle[i].stack) handle[i].stack.forEach(objMiddle){this.stack.push(objMiddle);}
      else this.stack.push({ handle: handle[i], method });
    }
  }
```

**Comment by hoangvvo** [comment]
Ooops, that is right. I was thinking that Array was also an Object (which is true), but doing `Object.assign` would replace the target Array since the target and source share the same indexes (0,1,2,...).

Could you do a PR?

**Comment by hoangvvo** [comment]
@GeinerGV Are you plannig to do a PR? If not, I will open one. Thanks!
