### ISSUE TITLE
Type error: try to use multer with next connect

### ISSUE THREAD

**Issue by DarlonHenrique** [hoangvvo/next-connect#216]
## Im trying to use next connect to my middlware but i have no idea how i can do this, because everything i try i have error

<img width="1680" alt="Screen Shot 2022-12-09 at 4 53 50 PM" src="https://user-images.githubusercontent.com/67025443/206786535-4bf35777-8f05-4021-bb55-395f055087ed.png">

<img width="1680" alt="Screen Shot 2022-12-09 at 5 00 43 PM" src="https://user-images.githubusercontent.com/67025443/206786844-b5145def-decd-4f06-b33e-f7d9669057c0.png">

**Comment by Zac-Zajdel** [comment]
Heads up @DarlonHenrique. I used this package for a bunch of projects but have started to move away. I know this does not help your answer but it seems like the package isn't getting updated anymore. I have recently switched to trpc and trust me. It makes next-connect look like vanilla JS and trpc the TypeScript equivalent.

**Comment by hoangvvo** [comment]
Sorry I missed this. Please see this: https://github.com/hoangvvo/nextjs-mongodb-app/blob/v2/pages/api/user/index.js#L91-L95
