### ISSUE TITLE
Add Next.js 14 Example with Implementation of next-connect

### ISSUE THREAD

**Issue by zehan12** [hoangvvo/next-connect#245]
Create a comprehensive example for Next.js 14, demonstrating the integration of next-connect for better understanding

**Comment by barbietunnie** [comment]
Here's an [example](https://github.com/hoangvvo/next-connect?tab=readme-ov-file#nextjs-app-router) that uses [Next.js 13/14 Route Handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) @zehan12.

**Comment by zehan12** [comment]
Thanks @barbietunnie
