### ISSUE TITLE
Absence of a repository with example

### ISSUE THREAD

**Issue by eakarpov** [hoangvvo/next-connect#29]
Please make a repo with a working example of your middleware connector.

I have a question - how should Next.js understand to include your handler exported from the file in its life cycle? Should I write something in next.config.js or should I properly name the file where nextConnect() is called... I don't fully understand. Please help me to use your package properly.

**Comment by Lite5h4dow** [comment]
https://github.com/hoangvvo/nextjs-mongodb-app here is his example repo.

**Comment by hoangvvo** [comment]
Thanks @Lite5h4dow. I added a note to README.
