### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by simonedelmann** [hoangvvo/next-connect#43]
I recently started to use next-connect, great work! 
The only thing I miss is typescript support.

**Comment by hoangvvo** [comment]
Definitely, I recently started working with TypeScript, so this can be helpful. Will get a PR in when I can.

**Comment by simonedelmann** [comment]
Great, I will wait for that! Thanks for your work!!
(If you have an estimated date, would be great for my planning...)

**Comment by hoangvvo** [comment]
@simonedelmann Hey, I bundle the definition in `0.6.4`. I'm not sure if it works because I do not really have much experience in TypeScript. If it doesn't, tell me and I will try to fix it. cheers

**Comment by simonedelmann** [comment]
@hoangvvo Thanks! Seems to work! (I am still struggling with passport.js middleware, but this is related to passport..)
