### ISSUE TITLE
Usage with next-iron-session

### ISSUE THREAD

**Issue by Kerumen** [hoangvvo/next-connect#46]
I try to use `next-connect` with [`next-iron-session`](https://github.com/vvo/next-iron-session/) but my API call stays in pending.

I don't know if the problem comes from this package or from the other, that's why I opened this issue and [another one](https://github.com/vvo/next-iron-session/issues/70) in `next-iron-session`.

```js
function withSession(handler) {
  return withIronSession(handler, {
    password: process.env.SECRET_COOKIE_PASSWORD,
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production' ? true : false,
    },
  })
}

const handler = nextConnect()

handler
  .use(withSession)
  .get(async (req, res) => {
    const user = req.session.get('user')
    res.json(user)
  })

export default handler
```

**Comment by hoangvvo** [comment]
Hey @Kerumen, `withIronSession` is used as a wrapper function, not a middleware. Try this:

```
function withSession(handler) {
  return withIronSession(handler, {
    password: process.env.SECRET_COOKIE_PASSWORD,
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production' ? true : false,
    },
  })
}

const handler = nextConnect()

handler
  .get(async (req, res) => {
    const user = req.session.get('user')
    res.json(user)
  })

export default withSession(handler)
```

**Comment by vvo** [comment]
Hey there, should I make this easier you think in next-iron-session? If so, how? Thanks

**Comment by hoangvvo** [comment]
@vvo I think offering a version for Express/Connect would be a good idea :+1: I just looked up and see nothing like a "express-session-iron".

**Comment by hoangvvo** [comment]
Ah, i see you bring that up in https://github.com/vvo/next-iron-session/issues/9

**Comment by vvo** [comment]
@Kerumen Are you up for that? (I think we can close this issue now..)

**Comment by vvo** [comment]
Thanks @hoangvvo!

**Comment by Kerumen** [comment]
> ```
> function withSession(handler) {
>   return withIronSession(handler, {
>     password: process.env.SECRET_COOKIE_PASSWORD,
>     cookieOptions: {
>       secure: process.env.NODE_ENV === 'production' ? true : false,
>     },
>   })
> }
> 
> const handler = nextConnect()
> 
> handler
>   .get(async (req, res) => {
>     const user = req.session.get('user')
>     res.json(user)
>   })
> 
> export default withSession(handler)
> ```

That was my initial implementation but I wanted to do something more "middleware"-ish. No problem, I will look forward for an update on `next-iron-session` to support that case in the future!

Thanks both of you.

**Comment by vvo** [comment]
This was solved in next-iron-session v4: https://github.com/vvo/next-iron-session/releases/tag/v4.0.0
