### ISSUE TITLE
`onError` fails to fire when using custom middleware

### ISSUE THREAD

**Issue by coogie** [hoangvvo/next-connect#49]
When using `next-connect` with custom or library middleware via the `.use` method, `onError` handler does not trigger.

## 🔹 Expected
Thrown error caught and handled by `next-connect` onError method

## 🔸 Actual
Thrown error not caught and crashes application

## 💻 Environment

 - Node: 'v10.16.3'
 - Platform: 'win32'
 - Arch: 'x64'

## 🌌 Minimal Reproduction Repo

https://github.com/coogie/next-connect-repro/commit/880a4dfc15e84d55ce1b2ede7dbb496a979d45ae

**Comment by hoangvvo** [comment]
Hey @coogie, thanks for such a detailed bug report (lovee the emoji :100:) It has been fixed in `v0.6.6`.
