### ISSUE TITLE
Use global middleware

### ISSUE THREAD

**Issue by oncet** [hoangvvo/next-connect#58]
Is it possible to have global middlewares? If so, what is the recommended way?

This is what I've tried so far.

```
// pages/api/index.js
import nextConnect from "next-connect";

const handler = nextConnect();

handler.use((req, res, next) => {
  console.log('foo');
  next();
});

export default handler;
```

And with the `base` param:

```
handler.use('/', (req, res, next) => {
  console.log('foo');
  next();
});
```

But when I access `/api/hello`, `foo` is not logged to the console.

```
// pages/api/hello.js
export default (req, res) => {
  res.statusCode = 200
  res.json({ name: 'John Doe' })
}
```

Thanks!

**Comment by ljosberinn** [comment]
that makes sense. its a different lambda and `api/hello` obviously wont first execute `api/index`. you can however build your own middleware that you'll have to use wherever you want. I have this one for example:

```js
import { Middleware } from 'next-connect';

import { BAD_REQUEST } from '../../../utils/statusCodes';

/**
 * Middleware accepting exclusively valid JSON as req.body, if existing
 */
export const expectJSONBodyMiddleware: Middleware = (req, res, next) => {
  if (req.body.length > 0) {
    try {
      req.body = JSON.parse(req.body);
    } catch (error) {
      console.error(error);
      return res.status(BAD_REQUEST).end();
    }
  }

  next();
};

```
```js
export const handler = nextConnect()
  .use(expectJSONBodyMiddleware)
  .get((req, res, next) => {

  });
```

**Comment by hoangvvo** [comment]
There is this https://github.com/hoangvvo/next-connect/issues/53 which may be feasible. However there seems to be an issue with that.

Next.js doc: https://nextjs.org/docs/api-routes/dynamic-api-routes#catch-all-api-routes

**Comment by oncet** [comment]
Using the approach suggested by @ljosberinn
