### ISSUE TITLE
Cannot find module 'next-connect' in Firebase functions logs

### ISSUE THREAD

**Issue by michaelwechsler** [hoangvvo/next-connect#60]
I am in the process of deploying my next.js app to firebase hosting/functions. After a perfectly fine working serve and a error-free deploy, I am seeing the following error in the Firebase functions logs, after calling my api:

> { Error: Cannot find module 'next-connect'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Module.require (internal/modules/cjs/loader.js:692:17) 
> at require (internal/modules/cjs/helpers.js:25:18)
> at Object.Zb5a (/workspace/dist/app/server/static/iotbXc4GvSgS3_9KfBWUD/pages/api/phrase/[slug].js:200:18)
> at __webpack_require__ (/workspace/dist/app/server/static/iotbXc4GvSgS3_9KfBWUD/pages/api/phrase/[slug].js:23:31)
> .....

my original src/app/api/phrase/[slug].js looks like this:
```
import nextConnect from "next-connect";
import middleware from "../../../middleware/database";

const handler = nextConnect();

handler.use(middleware);

handler.get(async (req, res) => {
  const {
    query: { slug },
  } = req;

  const dataModel = {
    _id: String,
    slug: String,
    source: String,
    languages: Array,
  };

  let doc = {};
  if (slug != null) {
    doc = await req.db.collection("phrases").findOne({ slug: slug });
  } else {
    doc = null;
  }
  if (doc != null) {
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");

    res.json({ success: true, data: doc });
  } else {
    doc = dataModel;
    res.json({ success: false, data: null });
  }
});

handler.post(async (req, res) => {
  res.json({ message: "post" });
});

handler.put(async (req, res) => {
  res.end({ message: "put" });
});

export default handler;

```

src/app/middleware/database.js

```
import { MongoClient } from "mongodb";

const route = ROUTE;
const client = new MongoClient(route, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

async function database(req, res, next) {
  if (!client.isConnected()) await client.connect();
  console.log("db connected");
  req.dbClient = client;
  req.db = client.db("public");
  return next();
}

export default database;
```

package.json
```
{
  "name": "XXX",
  "version": "0.1.1",
  "private": true,
  "scripts": {
    "dev:client": "next src/app",
    "dev:server": "babel src/server --out-dir dist/server --source-maps --watch",
    "dev": "npm run dev:client & npm run dev:server",
    "build:client": "next build src/app",
    "build:server": "babel src/server --out-dir dist/server --source-maps",
    "build": "npm run build:client && npm run build:server",
    "preserve": "npm run build",
    "serve": "cross-env NODE_ENV=production firebase serve --only functions,hosting",
    "predeploy": "rimraf dist/ && npm run build",
    "deploy": "cross-env NODE_ENV=production firebase deploy --only functions,hosting"
  },
  "main": "dist/server/index.js",
  "engines": {
    "node": "10"
  },
  "dependencies": {
    "@appbaseio/reactivesearch": "^3.8.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.4.1",
    "concurrently": "^5.2.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.6.2",
    "isomorphic-unfetch": "^3.0.0",
    "mongodb": "^3.5.7",
    "mongoose": "^5.9.14",
    "morgan": "^1.9.1",
    "next": "^9.3.6",
    "next-connect": "^0.7.0",
    "node-fetch": "^2.6.0",
    "react": "16.13.1",
    "react-bootstrap": "^1.0.1",
    "react-cookie-consent": "^3.0.0",
    "react-dom": "16.13.1",
    "react-helmet-async": "^1.0.6"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.2"
  }
}

```

Does someone have an idea, whats wrong?

**Comment by hoangvvo** [comment]
That's odd. I don't use `next-connect` so I'm not really sure. Did you have `next-connect` in `package.json` file in `src/app`? This may be related https://stackoverflow.com/questions/57342258/firebase-deploy-error-cannot-find-module-firebase

Does it work when you only have other dependencies?

**Comment by hoangvvo** [comment]
By the way, you should do `export default handler` instead.

**Comment by michaelwechsler** [comment]
Yes next-connect is listed in my package.json. My bad, I was reinstalling while I was preparing this post, that's why it was missing. Either way, I am getting the same error.

My firebase.json looks like this:
```
{
  "hosting": {
    "public": "src/public",
    "rewrites": [
      {
        "source": "**/**",
        "function": "next"
      }
    ]
  },
  "functions": {
    "source": ".",
    "ignore": [
      ".firebase/**",
      ".firebaserc",
      "firebase.json",
      "**/node_modules/**",
      "**/public/**"
    ]
  }
}
```
That's why it should be enough that I have next-connect in my package.json on project root.

Is next-connect supported by firebase functions?

**Comment by michaelwechsler** [comment]
> By the way, you should do `export default handler` instead.
Thanks a lot! I changed it.

**Comment by michaelwechsler** [comment]
> That's odd. I don't use `next-connect` so I'm not really sure. Did you have `next-connect` in `package.json` file in `src/app`? This may be related https://stackoverflow.com/questions/57342258/firebase-deploy-error-cannot-find-module-firebase
> 
> Does it work when you only have other dependencies?

I can deploy without problem. No Error.

But I have this error in firebase console.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/23740606/83721476-6d953e00-a63b-11ea-9ce4-09fea41e8086.png">

**Comment by hoangvvo** [comment]
`next-connect` is no different from other regular npm package so it should be supported. Can you install and use any other npm package in your firebase app?

**Comment by hoangvvo** [comment]
Which `package.json` do you have `next-connect` included? I don't use Firebase but I read that they have different `package.json` in `hosting` and `functions` folders (correct me if I'm wrong). can you try installing `next-connect` in each of them?

**Comment by michaelwechsler** [comment]
I will look into this! Right now I am using a global package.json for all of them. I will try to split it into two different ones and will see. Afaik there shouldn't be a difference (than cleaner code). Thanks a lot for your support @hoangvvo !!!

**Comment by hoangvvo** [comment]
You're welcome. This is what I'm referring to: https://stackoverflow.com/a/57342623
