### ISSUE TITLE
Handling errors that are thrown in onNoMatch handler

### ISSUE THREAD

**Issue by edshav** [hoangvvo/next-connect#65]
It's a Feature request.

`options.onError` function could catch errors that are thrown in `options.onNoMatch` handler. So in a project we could explicitly throw custom error in onNoMatch function.
As a result, all errors will be processed in а single place.

```
import { NotFoundError } from 'errors/not-found-error';

export const onNoMatch = (): void => {
  throw new NotFoundError();
};

```

**Comment by hoangvvo** [comment]
I think this does make sense. I will try to put together a PR soon!

**Comment by Tymek** [comment]
I'm not sure if this is is needed. I used custom Error with `onError` to set `status` in my code. Maybe an example patter in documentations is a better idea. My excerpt:
``` js
export const onError = (err: ActionErrorType, req: NextApiRequest, res: NextApiResponse): void => {
	if (err.code && typeof err.code === 'number') {
		res.status(err.code)
	} else {
		res.status(400)
	}

	res.json(err)
}
```
