### ISSUE TITLE
Typescript errors when used in /pages

### ISSUE THREAD

**Issue by l0h1t** [hoangvvo/next-connect#68]
I'm getting the below typescript error when I use **handler.apply** method inside pages

```
Argument of type 'IncomingMessage' is not assignable to parameter of type 'NextApiRequest'.
  Type 'IncomingMessage' is missing the following properties from type '{ query: { [key: string]: string | string[]; }; cookies: { [key: string]: string; }; body: any; }': query, cookies, body
```

So, inside the **getServerSideProps/getInitialProps** method the req and res we get from context are of type Incoming message and ServerResponse respectively and I'm not able to run the handler because of this issue

**Comment by hoangvvo** [comment]
I just changed the types to `IncomingMessage` and `ServerResponse` in `0.7.2`

**Comment by l0h1t** [comment]
Yes it works now thanks!
