### ISSUE TITLE
use with getStaticProps?

### ISSUE THREAD

**Issue by warcraft14115** [hoangvvo/next-connect#71]
hi, next-connect can't use with getStaticProps? I don't think I did something wrong.
```
export const getStaticProps = async ({req,res}) => {
   const handler= nextConnect()
   handler.use(database)
   await handler.apply(req,res)
   let items = await getProducts(req,0,8);
   return {
      props: { items },
   };
};
```
![image](https://user-images.githubusercontent.com/15695252/85919653-7f16e200-b897-11ea-9bd1-241fc9147184.png)

**Comment by ljosberinn** [comment]
shouldn't it be `await handler.apply(null, [req, res])` or `await handler.apply(handler, [req, res])`?

**Comment by warcraft14115** [comment]
@ljosberinn I follow docs, I use old version 0.6.6 I work fine with serverside props

![image](https://user-images.githubusercontent.com/15695252/85924373-19891c80-b8bc-11ea-9066-c8d5fb60895e.png)

**Comment by ljosberinn** [comment]
oh right sorry - what error do you see?

**Comment by hoangvvo** [comment]
In `getStaticProps`, there is no `req` and `res` ([link](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)). I think your usage is not correct. What are you trying to achieve?

**Comment by hoangvvo** [comment]
> shouldn't it be `await handler.apply(null, [req, res])` or `await handler.apply(handler, [req, res])`?

Seems like `.apply` is an awful API since it rewrites `Function.apply`. :no_good: Maybe this needs to be renamed in a breaking ver

**Comment by warcraft14115** [comment]
> > shouldn't it be `await handler.apply(null, [req, res])` or `await handler.apply(handler, [req, res])`?
> 
> Seems like `.apply` is an awful API since it rewrites `Function.apply`. 🙅 Maybe this needs to be renamed in a breaking ver

Sorry for this. Silly question. I query direct to mongodb
