### ISSUE TITLE
No `status` property on ServerResponse

### ISSUE THREAD

**Issue by switz** [hoangvvo/next-connect#72]
```
26:14 Property 'status' does not exist on type 'ServerResponse'.
    24 |   res.setHeader('Location', '/');
    25 |
  > 26 |   return res.status(302).end();
       |              ^
    27 | });
    28 |
    29 | export default handler;
```

Any suggestions?

**Comment by hoangvvo** [comment]
Are you using v0.7.2, can you downgrade to v0.7.1 for now?

**Comment by ljosberinn** [comment]
Same as #69, you can use [this](https://github.com/hoangvvo/next-connect/issues/69#issuecomment-650396465) solution, downgrade to 0.7.1 or wait until #70 is merged.

**Comment by switz** [comment]
Not a problem, I wrapped my types in the meantime. Thanks for the quick reply!
