### ISSUE TITLE
RequestHandler return type

### ISSUE THREAD

**Issue by Tymek** [hoangvvo/next-connect#74]
Documentation states, that `get` can be called with `async` function. `async` always returns a promise. Am I correct to assume, that `RequestHandler` should have type of `void | Promise<void>` in this case, or maybe generic `<X: any>` like Trouter? The same with `ErrorHandler`.

PR welcome?

**Comment by hoangvvo** [comment]
Thanks for pointing it out. PR is always welcome!

**Comment by hoangvvo** [comment]
Let's do `any`

**Comment by Tymek** [comment]
After grasping what code does, I think return value from handler is never taken into account.
``` diff
diff --git a/lib/index.js b/lib/index.js
index 2846bf7..2e16193 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -67,7 +67,7 @@ module.exports = ({
           : loop().catch(next)
         : done && done(err);
     async function loop() {
-      return handlers[i++](req, res, next);
+      await handlers[i++](req, res, next);
     }
     next();
   };
```

When using TS I expect type-checking to be strict.
Wrapping an incompatible handler in `(req, res, next) => { handler(req, res, next) }` will change return type to `void`.
With `async (req, res, next) => { await handler(req, res, next) }` into `Promise<void>`  accordingly

Therefore I think we should use `void | Promise<void>`.
